### ISSUE TITLE
Fejl v. indlæsning af adresser

### ISSUE THREAD

**Issue by styrke10** [mapcentia/DAWAreplicator#1]
Hej Martin,

Jeg har testet din adresse-replikator, men løber desværre ind i en fejl, når jeg afvikler rutinen første gang - se nedenfor:
-----------------------
C:\>java -jar DAWAreplicator.jar config.yml init
Connecting to database: jdbc:postgresql://192.168.1.165:5432/DAR

sekvensnummer: 3252503   Tid: 2017-06-18T01:00:33.136Z

Indsætter adresser... 3638343
Indsætter adgangsadresser... 0Exception in thread "main" java.lang.NumberFormatException: For input string: "d90e9338-0470-41bc-8ecb-6f71dd912ff0"
        at sun.misc.FloatingDecimal.readJavaFormatString(Unknown Source)
        at sun.misc.FloatingDecimal.parseFloat(Unknown Source)
        at java.lang.Float.parseFloat(Unknown Source)
        at java.lang.Float.valueOf(Unknown Source)
        at com.mapcentia.aws_sync.AdgangsAdresserInit.get(AdgangsAdresserInit.java:66)
        at com.mapcentia.aws_sync.ReplicaInit.start(ReplicaInit.java:56)
        at com.mapcentia.aws_sync.Main.main(Main.java:25)
-----------------------

Jeg lurer på, om det eventuelt hænger sammen med adgangspunktid, som jeg kan se er tilføjet sidst i udviklingsprocessen. Dette felt bliver IKKE oprettet i min PostGIS database. Og - baseret på min begrænsede erfaring på Java - tyder jeg ovenstående fejl derhen, at id'en, der modtages som streng forsøges konverteret til float, hvilket passer med næste felt; etrs89koordinat_oest.

Kan det måske tænkes, at den distribuerede jar-fil ikke er kompileret på nyeste `source-filer?```

**Comment by mapcentia** [comment]
Jo, det er jar-filen, som er "gamle" og har ikke "adgangspunktid" med . Jeg har lige pushed en ny. Du bliver nød til at droppe de tabeller, der er oprettet og køre igen.
